# -*- coding: utf-8 -*-
"""pilot2_step4_text_to_paragraph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IoyIZGDyPBr6sA30UrqCeeY9q2NVz-kW
"""

from google.colab import files
import os
import shutil
import zipfile

uploaded = files.upload()

print("Uploaded files：", list(uploaded.keys()))

import os
import shutil
import zipfile

# Colab local runtime directory
LOCAL_BASE = "/content/linear_probe/pilot_2"
LOCAL_DATA_DIR = f"{LOCAL_BASE}/data"
LOCAL_INPUT_DIR = f"{LOCAL_DATA_DIR}/step3_text"

# Step 4 output directory
LOCAL_OUTPUT_DIR = "/content/step4_text_refine_with_olmo2"

os.makedirs(LOCAL_DATA_DIR, exist_ok=True)
os.makedirs(LOCAL_OUTPUT_DIR, exist_ok=True)

zip_path = "/content/step3_text.zip"

if not os.path.exists(zip_path):
    raise FileNotFoundError(
        "Could not find /content/step3_text.zip.\n"
        "Please run the previous cell first and upload the step3_text.zip file from your computer."
    )

print("Detected zip file:", zip_path)

# Clean up old directory
if os.path.exists(LOCAL_INPUT_DIR):
    shutil.rmtree(LOCAL_INPUT_DIR)

extract_tmp = f"{LOCAL_DATA_DIR}/_extract_tmp"
if os.path.exists(extract_tmp):
    shutil.rmtree(extract_tmp)
os.makedirs(extract_tmp, exist_ok=True)

with zipfile.ZipFile(zip_path, "r") as zf:
    zf.extractall(extract_tmp)

entries = os.listdir(extract_tmp)
if len(entries) == 1 and os.path.isdir(os.path.join(extract_tmp, entries[0])):
    inner_dir = os.path.join(extract_tmp, entries[0])
    shutil.move(inner_dir, LOCAL_INPUT_DIR)
else:
    os.makedirs(LOCAL_INPUT_DIR, exist_ok=True)
    for name in entries:
        shutil.move(os.path.join(extract_tmp, name), os.path.join(LOCAL_INPUT_DIR, name))

shutil.rmtree(extract_tmp)

print("Local input directory is ready:", LOCAL_INPUT_DIR)
print("Directory contents (first 10 items):", os.listdir(LOCAL_INPUT_DIR)[:10])

import os

os.environ["HF_HOME"] = "/content/hf_cache"
os.environ["TRANSFORMERS_CACHE"] = "/content/hf_cache"
os.environ["PIP_CACHE_DIR"] = "/content/pip_cache"

print("HF_HOME =", os.environ["HF_HOME"])
print("TRANSFORMERS_CACHE =", os.environ["TRANSFORMERS_CACHE"])
print("PIP_CACHE_DIR =", os.environ["PIP_CACHE_DIR"])

print("\nChecking remaining space in /content:")
!df -h /content

!pip install -q --no-cache-dir transformers accelerate sentencepiece safetensors
!pip install -q bitsandbytes

import torch
import os

print("torch.cuda.is_available() =", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU count =", torch.cuda.device_count())
    print("GPU name  =", torch.cuda.get_device_name(0))
else:
    print("No GPU available, the model will fall back to CPU")

!nvidia-smi

INPUT_DIR = "/content/linear_probe/pilot_2/data/step3_text"
OUTPUT_DIR = "/content/step4_text_refine_with_olmo2"
HF_CACHE_DIR = "/content/hf_cache"

print("INPUT_DIR =", INPUT_DIR)
print("OUTPUT_DIR =", OUTPUT_DIR)
print("HF_CACHE_DIR =", HF_CACHE_DIR)

# -*- coding: utf-8 -*-

import json
import os
import re
import time
from pathlib import Path
from typing import Dict, List, Any

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

# User-configurable settings

MODEL_NAME = "allenai/OLMo-2-1124-7B-Instruct"

INPUT_DIR = "/content/linear_probe/pilot_2/data/step3_text"
OUTPUT_DIR = "/content/step4_text_refine_with_olmo2"
HF_CACHE_DIR = "/content/hf_cache"

USE_4BIT = True

MAX_NEW_TOKENS = 320

MAX_WORDS_PER_PARAGRAPH = 220

MAX_SENTENCES_PER_BATCH = 6

DO_SAMPLE = False
TEMPERATURE = 0.3
TOP_P = 0.9

OVERWRITE = True


# Utility helpers

def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def load_json(path: str) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def save_json(path: str, data: Dict[str, Any]) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def normalize_text(text: str) -> str:
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def build_fact_list(sentences: List[str]) -> str:
    return "\n".join(f"{i}. {sent}" for i, sent in enumerate(sentences, start=1))


def extract_assistant_text(generated_text: str) -> str:
    text = generated_text.strip()

    prefixes = [
        "assistant\n",
        "assistant:",
        "Assistant:",
        "Rewritten paragraph:",
        "Paragraph:",
        "Output:",
    ]
    for p in prefixes:
        if text.startswith(p):
            text = text[len(p):].strip()

    text = text.strip("`").strip()
    return text


def count_words(text: str) -> int:
    return len(re.findall(r"\b\w+\b", text))


def split_into_sentences_for_trim(text: str) -> List[str]:
    text = normalize_text(text)
    if not text:
        return []
    parts = re.split(r'(?<=[.!?])\s+', text)
    return [p.strip() for p in parts if p.strip()]


def trim_to_word_limit_keep_full_sentences(text: str, max_words: int) -> str:
    sentences = split_into_sentences_for_trim(text)
    if not sentences:
        return ""

    kept = []
    total = 0

    for sent in sentences:
        sent_words = count_words(sent)
        if total + sent_words <= max_words:
            kept.append(sent)
            total += sent_words
        else:
            break

    if kept:
        return " ".join(kept).strip()

    words = re.findall(r"\S+", text)
    return " ".join(words[:max_words]).strip()


def chunk_scene_data(scene_data: Dict[str, Any], max_sentences_per_batch: int) -> List[Dict[str, Any]]:
    all_sentences = scene_data.get("sentences", []) or []
    all_text_records = scene_data.get("text_records", []) or []
    full_alias_map = scene_data.get("entity_alias_map", {}) or {}
    scene = scene_data.get("scene", "UNKNOWN_SCENE")

    if not all_sentences:
        paragraph = scene_data.get("paragraph", "").strip()
        return [{
            "scene": scene,
            "paragraph": paragraph,
            "sentences": [],
            "text_records": [],
            "entity_alias_map": {},
            "num_sentences": 0,
            "num_selected_relations": scene_data.get("num_selected_relations"),
            "chunk_id": 1,
            "num_chunks": 1,
        }]

    chunks = []
    total_chunks = (len(all_sentences) + max_sentences_per_batch - 1) // max_sentences_per_batch

    for i in range(0, len(all_sentences), max_sentences_per_batch):
        batch_sentences = all_sentences[i:i + max_sentences_per_batch]
        batch_text_records = all_text_records[i:i + max_sentences_per_batch]
        chunk_id = len(chunks) + 1

        used_ids = set()
        for rec in batch_text_records:
            if "subject_id" in rec:
                used_ids.add(rec["subject_id"])
            if "object_id" in rec:
                used_ids.add(rec["object_id"])

        batch_alias_map = {
            obj_id: alias
            for obj_id, alias in full_alias_map.items()
            if obj_id in used_ids
        }

        chunks.append({
            "scene": scene,
            "paragraph": " ".join(batch_sentences).strip(),
            "sentences": batch_sentences,
            "text_records": batch_text_records,
            "entity_alias_map": batch_alias_map,
            "num_sentences": len(batch_sentences),
            "num_selected_relations": len(batch_sentences),
            "chunk_id": chunk_id,
            "num_chunks": total_chunks,
        })

    return chunks


def build_prompt(scene_data: Dict[str, Any]) -> List[Dict[str, str]]:
    scene = scene_data.get("scene", "UNKNOWN_SCENE")
    paragraph = scene_data.get("paragraph", "").strip()
    sentences = scene_data.get("sentences", [])
    fact_list = build_fact_list(sentences)
    chunk_id = scene_data.get("chunk_id", 1)
    num_chunks = scene_data.get("num_chunks", 1)

    entity_alias_map = scene_data.get("entity_alias_map", {}) or {}
    text_records = scene_data.get("text_records", []) or {}

    # Provide only aliases, not the original object_id, to avoid leaking coordinates.
    alias_names = sorted(entity_alias_map.values())
    alias_text = "\n".join(f"- {alias}" for alias in alias_names).strip()

    # Provide only alias-level structured relations, without exposing original IDs.
    record_lines = []
    for i, rec in enumerate(text_records, start=1):
        subj = rec.get("subject_alias", "UNKNOWN_SUBJECT")
        rel = rec.get("relation", "UNKNOWN_RELATION")
        obj = rec.get("object_alias", "UNKNOWN_OBJECT")
        record_lines.append(f"{i}. {subj} --{rel}--> {obj}")
    structured_fact_text = "\n".join(record_lines).strip()

    system_prompt = (
        "You are a careful rewriting assistant for spatial scene descriptions.\n"
        "Your task is to rewrite a rule-based paragraph into a more natural, fluent paragraph.\n"
        "You must preserve the original meaning exactly.\n"
        "Object aliases such as drawer_1 and drawer_2 refer to different physical instances and must never be merged.\n"
        "Never output raw object IDs, coordinates, or strings containing the pipe character '|'."
    )

    user_prompt = f"""
Scene: {scene}
Batch: {chunk_id}/{num_chunks}

Task:
Rewrite this batch of spatial facts into ONE English paragraph.

Goal:
Produce a simple and literal paragraph that preserves the original spatial relationships as accurately as possible.
Avoid descriptive or interpretive language.

Allowed object names in this batch:
{alias_text if alias_text else "None provided."}

Structured relations in this batch:
{structured_fact_text if structured_fact_text else "None provided."}

Guidelines:

1. COVER ALL RELATIONS
- Every distinct input relation must appear at least once in the output.
- You may omit exact duplicates, but no distinct relation may be missing.

2. PRESERVE SPATIAL MEANING
- Keep the original spatial relationships correct.
- You may express a relation in its equivalent opposite form if needed.
  (Example: "A is above B" ↔ "B is below A" is acceptable.)

3. USE ONLY THE PROVIDED ALIASES (CRITICAL)
- Only use object names from the "Allowed object names" list.
- Never output raw object IDs.
- Never output coordinates.
- Never output strings containing "|" or signed numbers such as +00.95 or -02.20.

4. DO NOT WEAKEN OR SUBSTITUTE RELATIONS (CRITICAL)
- Keep relation words as close as possible to the input.
- Do NOT replace precise relation terms with paraphrases.

Forbidden substitutions:
- "to the right of" → "near", "next to", "beside"
- "to the left of" → "near", "next to", "beside"
- "above" → "over", "on top of"
- "near" → "close to", "adjacent to"
- "in" → "inside of"
- "on" → "resting on"
- Do not use: "situated", "positioned", "located", "shares its space with"

5. DO NOT ADD NEW RELATIONS
- If a relation is not explicitly stated in the input, do NOT mention it.
- Do NOT infer or derive new relations from combinations of facts.

6. DO NOT ADD NEW OBJECTS
- Only use objects that appear in the input.
- Do NOT introduce any additional entities.

7. DO NOT MERGE OBJECT INSTANCES (CRITICAL)
- Different aliases always refer to different physical objects.
- Never merge drawer_1 and drawer_2 into one drawer.
- Never treat cabinet_1 and cabinet_2 as the same object.

8. KEEP OBJECT NAMES EXACT (CRITICAL)
- Preserve aliases exactly as written.
- Keep lowercase letters, underscores, and numeric suffixes unchanged.
- For example, keep "drawer_3" exactly as "drawer_3".
- Do not output "Drawer_3", "drawer 3", or "drawer-3".

9. USE SIMPLE AND LITERAL LANGUAGE
- Use direct and explicit sentence structures.
- Avoid descriptive, narrative, or interpretive wording.
- Avoid words such as:
  "arrangement", "layout", "positioned around", "flank", "surround",
  "maintaining order", "within the confines", "accurately positioned"

10. NO STRUCTURAL DISTORTION
- Do NOT combine facts in a way that changes their meaning.
- Each relation must clearly connect the correct subject and object.

11. STOP CONDITION
- Stop after all input relations have been expressed.
- Do not continue with general scene description.

12. STRUCTURE
- Write exactly ONE paragraph.
- Prefer short, literal clauses.
- Slight repetition is acceptable.

Output:
Return exactly one paragraph. No explanations.

Numbered spatial facts for this batch:
{fact_list}

Original step3 paragraph for this batch:
{paragraph}

Return only the rewritten paragraph for this batch.
""".strip()

    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]


def load_model_and_tokenizer(model_name: str, use_4bit: bool = False):
    tokenizer = AutoTokenizer.from_pretrained(
        model_name,
        trust_remote_code=True,
        cache_dir=HF_CACHE_DIR,
    )

    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model_kwargs = {
        "trust_remote_code": True,
        "device_map": "auto",
        "cache_dir": HF_CACHE_DIR,
    }

    if use_4bit:
        from transformers import BitsAndBytesConfig

        compute_dtype = torch.bfloat16 if torch.cuda.is_available() else torch.float32

        model_kwargs["quantization_config"] = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=compute_dtype,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type="nf4",
        )
    else:
        model_kwargs["torch_dtype"] = torch.bfloat16 if torch.cuda.is_available() else torch.float32

    model = AutoModelForCausalLM.from_pretrained(model_name, **model_kwargs)
    model.eval()
    return tokenizer, model


@torch.no_grad()
def generate_rewrite(
    tokenizer,
    model,
    scene_data: Dict[str, Any],
    max_new_tokens: int = 320,
    do_sample: bool = False,
    temperature: float = 0.3,
    top_p: float = 0.9,
    max_words_per_paragraph: int = 220,
) -> Dict[str, Any]:
    messages = build_prompt(scene_data)

    if hasattr(tokenizer, "apply_chat_template"):
        prompt_text = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
        )
    else:
        prompt_text = (
            f"System: {messages[0]['content']}\n\n"
            f"User: {messages[1]['content']}\n\n"
            f"Assistant:"
        )

    inputs = tokenizer(
        prompt_text,
        return_tensors="pt",
        truncation=True,
    )

    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    generation_kwargs = {
        "max_new_tokens": max_new_tokens,
        "do_sample": do_sample,
        "pad_token_id": tokenizer.pad_token_id,
        "eos_token_id": tokenizer.eos_token_id,
    }

    if do_sample:
        generation_kwargs["temperature"] = temperature
        generation_kwargs["top_p"] = top_p

    output_ids = model.generate(**inputs, **generation_kwargs)

    prompt_len = inputs["input_ids"].shape[1]
    new_tokens = output_ids[0][prompt_len:]
    decoded = tokenizer.decode(new_tokens, skip_special_tokens=True)
    rewritten_raw = normalize_text(extract_assistant_text(decoded))

    rewritten_trimmed = trim_to_word_limit_keep_full_sentences(
        rewritten_raw,
        max_words=max_words_per_paragraph,
    )

    input_aliases = set(scene_data.get("entity_alias_map", {}).values())
    source_text = " ".join(scene_data.get("sentences", []))

    missing_aliases = [
        alias
        for alias in input_aliases
        if alias in source_text and alias not in rewritten_trimmed
    ]

    # Check for leakage of original object IDs or coordinate-like patterns.
    leaked_raw_ids = bool(re.search(r"[A-Za-z]+\|[+-]\d+\.\d+\|[+-]\d+\.\d+\|[+-]\d+\.\d+", rewritten_trimmed))
    leaked_pipe = "|" in rewritten_trimmed

    # Check whether aliases have been rewritten into disallowed formats (e.g., Drawer_1 or drawer 1).
    alias_format_violations = []
    for alias in input_aliases:
        alias_space = alias.replace("_", " ")
        alias_title = alias[0].upper() + alias[1:] if alias else alias

        if alias not in rewritten_trimmed:
            if alias_space in rewritten_trimmed or alias_title in rewritten_trimmed:
                alias_format_violations.append(alias)

    if missing_aliases:
        print(f"  [Warn] Missing aliases in output: {missing_aliases}")
    if leaked_raw_ids or leaked_pipe:
        print("  [Warn] Raw object ID or coordinate-like text leaked into output.")
    if alias_format_violations:
        print(f"  [Warn] Alias format changed in output: {alias_format_violations}")

    return {
        "prompt_text": prompt_text,
        "rewritten_paragraph_raw": rewritten_raw,
        "rewritten_paragraph": rewritten_trimmed,
        "rewritten_word_count_raw": count_words(rewritten_raw),
        "rewritten_word_count_final": count_words(rewritten_trimmed),
        "missing_aliases": missing_aliases,
        "leaked_raw_ids": leaked_raw_ids,
        "leaked_pipe": leaked_pipe,
        "alias_format_violations": alias_format_violations,
    }


def build_output_record(
    scene_data: Dict[str, Any],
    generation_results: List[Dict[str, Any]]
) -> Dict[str, Any]:
    rewritten_paragraphs = [x["rewritten_paragraph"] for x in generation_results]
    rewritten_paragraph_raw_list = [x["rewritten_paragraph_raw"] for x in generation_results]

    return {
        "scene": scene_data.get("scene"),
        "model_family": "OLMo",
        "model_name": MODEL_NAME,

        "input_num_sentences": scene_data.get("num_sentences"),
        "input_num_selected_relations": scene_data.get("num_selected_relations"),
        "input_paragraph": scene_data.get("paragraph", ""),
        "input_sentences": scene_data.get("sentences", []),
        "input_text_records": scene_data.get("text_records", []),
        "input_entity_alias_map": scene_data.get("entity_alias_map", {}),

        "rewritten_paragraphs": rewritten_paragraphs,
        "rewritten_paragraph": "\n\n".join(rewritten_paragraphs),

        "metadata": {
            "max_new_tokens": MAX_NEW_TOKENS,
            "max_words_per_paragraph": MAX_WORDS_PER_PARAGRAPH,
            "max_sentences_per_batch": MAX_SENTENCES_PER_BATCH,
            "do_sample": DO_SAMPLE,
            "temperature": TEMPERATURE if DO_SAMPLE else None,
            "top_p": TOP_P if DO_SAMPLE else None,
            "num_output_paragraphs": len(rewritten_paragraphs),
            "raw_word_counts": [x["rewritten_word_count_raw"] for x in generation_results],
            "final_word_counts": [x["rewritten_word_count_final"] for x in generation_results],
            "missing_aliases_per_batch": [x.get("missing_aliases", []) for x in generation_results],
            "leaked_raw_ids_per_batch": [x.get("leaked_raw_ids", False) for x in generation_results],
            "leaked_pipe_per_batch": [x.get("leaked_pipe", False) for x in generation_results],
            "alias_format_violations_per_batch": [x.get("alias_format_violations", []) for x in generation_results],
            "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        },

        "rewritten_paragraphs_raw": rewritten_paragraph_raw_list,
    }


def process_file(
    input_path: Path,
    output_dir: Path,
    tokenizer,
    model,
) -> None:
    scene_data = load_json(str(input_path))
    scene_name = scene_data.get("scene", input_path.stem)

    output_filename = f"{scene_name}_olmo2_refined.json"
    output_path = output_dir / output_filename

    if output_path.exists() and not OVERWRITE:
        print(f"[Skip] {output_filename} already exists.")
        return

    print(f"[Run ] Processing {input_path.name} ...")

    batches = chunk_scene_data(
        scene_data=scene_data,
        max_sentences_per_batch=MAX_SENTENCES_PER_BATCH,
    )

    generation_results = []

    for batch in batches:
        chunk_id = batch.get("chunk_id", 1)
        num_chunks = batch.get("num_chunks", 1)
        print(f"  [Batch {chunk_id}/{num_chunks}] Generating...")

        result = generate_rewrite(
            tokenizer=tokenizer,
            model=model,
            scene_data=batch,
            max_new_tokens=MAX_NEW_TOKENS,
            do_sample=DO_SAMPLE,
            temperature=TEMPERATURE,
            top_p=TOP_P,
            max_words_per_paragraph=MAX_WORDS_PER_PARAGRAPH,
        )

        generation_results.append(result)

        print(
            f"  [Batch {chunk_id}/{num_chunks}] Done. "
            f"final_words={result['rewritten_word_count_final']}"
        )

    out_data = build_output_record(scene_data, generation_results)
    save_json(str(output_path), out_data)

    print(f"[Done] Saved to {output_path}")


# Split execution helpers

def prepare_inference():
    input_dir = Path(INPUT_DIR)
    output_dir = Path(OUTPUT_DIR)

    ensure_dir(str(output_dir))

    input_files = sorted(input_dir.glob("*_text.json"))
    if not input_files:
        raise FileNotFoundError(f"No *_text.json files found in: {input_dir}")

    print("=" * 80)
    print("Preparing inference...")
    print(f"MODEL_NAME   = {MODEL_NAME}")
    print(f"INPUT_DIR    = {input_dir}")
    print(f"OUTPUT_DIR   = {output_dir}")
    print(f"HF_CACHE_DIR = {HF_CACHE_DIR}")
    print(f"USE_4BIT     = {USE_4BIT}")
    print(f"NUM_FILES    = {len(input_files)}")
    print("=" * 80)

    tokenizer, model = load_model_and_tokenizer(MODEL_NAME, USE_4BIT)

    print("=" * 80)
    print("Model loaded successfully.")
    print("=" * 80)

    return tokenizer, model, input_files, output_dir


def run_inference(input_files, output_dir, tokenizer, model):
    print("=" * 80)
    print(f"Running inference on {len(input_files)} files...")
    print("=" * 80)

    for input_path in input_files:
        process_file(
            input_path=input_path,
            output_dir=output_dir,
            tokenizer=tokenizer,
            model=model,
        )

    print("=" * 80)
    print("All files processed.")
    print("=" * 80)

tokenizer, model, input_files, output_dir = prepare_inference()

run_inference(input_files, output_dir, tokenizer, model)

for name in os.listdir("/content/step4_text_refine_with_olmo2"):
    print(name)

!zip -r /content/step4_outputs.zip /content/step4_text_refine_with_olmo2

from google.colab import files
files.download("/content/step4_outputs.zip")