# -*- coding: utf-8 -*-
"""pilot2_step6_probe_object_pair_ridge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17bFLiaMO6hlyZQb-pTwWiNxDbY45TavI
"""

!pip install -q scikit-learn

from google.colab import files

uploaded = files.upload()
print("Uploaded files:", list(uploaded.keys()))

import os
import shutil
import zipfile

BASE_DIR = "/content/pilot2_qwen_probe"
PT_DIR = os.path.join(BASE_DIR, "outputs_object_pair_sentence")

os.makedirs(BASE_DIR, exist_ok=True)

zip_files = [f for f in os.listdir("/content") if f.endswith(".zip")]
if not zip_files:
    raise FileNotFoundError("No zip file detected. Please upload object_pair_outputs.zip first.")

zip_path = os.path.join("/content", zip_files[0])
print("Using zip file:", zip_path)

# Clean up old directory
if os.path.exists(PT_DIR):
    shutil.rmtree(PT_DIR)

tmp_dir = os.path.join(BASE_DIR, "_tmp_extract")
if os.path.exists(tmp_dir):
    shutil.rmtree(tmp_dir)
os.makedirs(tmp_dir, exist_ok=True)

with zipfile.ZipFile(zip_path, "r") as zf:
    zf.extractall(tmp_dir)

entries = os.listdir(tmp_dir)
if len(entries) == 1 and os.path.isdir(os.path.join(tmp_dir, entries[0])):
    inner_dir = os.path.join(tmp_dir, entries[0])
    shutil.move(inner_dir, PT_DIR)
else:
    os.makedirs(PT_DIR, exist_ok=True)
    for name in entries:
        shutil.move(os.path.join(tmp_dir, name), os.path.join(PT_DIR, name))

shutil.rmtree(tmp_dir)

print("Extraction completed")
print("PT_DIR =", PT_DIR)
print("Sample files:", os.listdir(PT_DIR)[:5])

import json
from pathlib import Path
from typing import Dict, Any, List

import numpy as np
import torch

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score
from sklearn.preprocessing import LabelEncoder

OUTPUT_JSON = "/content/object_pair_relation_probe_results.json"

TRAIN_RATIO = 0.8
RANDOM_SEED = 42
MAX_ITER = 2000

np.random.seed(RANDOM_SEED)

print("PT_DIR =", PT_DIR)

def load_pt(path: str) -> Dict[str, Any]:
    return torch.load(path, map_location="cpu")


def make_json_safe(obj):
    if isinstance(obj, dict):
        return {k: make_json_safe(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [make_json_safe(v) for v in obj]
    elif isinstance(obj, tuple):
        return [make_json_safe(v) for v in obj]
    elif isinstance(obj, np.ndarray):
        return obj.tolist()
    elif isinstance(obj, (np.float32, np.float64)):
        return float(obj)
    elif isinstance(obj, (np.int32, np.int64)):
        return int(obj)
    else:
        return obj

def load_dataset_from_pt_dir(pt_dir: str, feature_key="layer_diff_features"):
    pt_files = sorted(Path(pt_dir).rglob("*.pt"))
    if not pt_files:
        raise FileNotFoundError("No .pt files found")

    all_scene_names = []
    all_relations = []
    all_layer_features = None
    metadata = []

    for pt_path in pt_files:
        obj = load_pt(str(pt_path))
        scene = obj["scene"]
        records = obj["sentence_pair_records"]

        for rec in records:
            relation = rec["relation"]
            feats = rec[feature_key]

            if all_layer_features is None:
                num_layers = feats.shape[0]
                all_layer_features = [[] for _ in range(num_layers)]

            for l in range(feats.shape[0]):
                all_layer_features[l].append(
                    feats[l].float().numpy()
                )

            all_scene_names.append(scene)
            all_relations.append(relation)

            metadata.append({
                "scene": scene,
                "relation": relation,
                "sentence": rec["sentence"]
            })

    X_layers = [np.stack(v, axis=0) for v in all_layer_features]
    y_text = np.array(all_relations)

    return all_scene_names, X_layers, y_text, metadata

def split_by_scene(scene_names, train_ratio=TRAIN_RATIO):
    unique = sorted(set(scene_names))
    n_train = int(len(unique) * train_ratio)

    train_scenes = set(unique[:n_train])
    test_scenes = set(unique[n_train:])

    train_idx = np.array([i for i, s in enumerate(scene_names) if s in train_scenes])
    test_idx = np.array([i for i, s in enumerate(scene_names) if s in test_scenes])

    return train_idx, test_idx, list(train_scenes), list(test_scenes)

def compute_metrics(y_true, y_pred, split_name):
    return {
        "split": split_name,
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "macro_f1": float(f1_score(y_true, y_pred, average="macro"))
    }


def train_and_eval(X_train, y_train, X_test, y_test):
    clf = LogisticRegression(max_iter=MAX_ITER)
    clf.fit(X_train, y_train)

    return {
        "train": compute_metrics(y_train, clf.predict(X_train), "train"),
        "test": compute_metrics(y_test, clf.predict(X_test), "test")
    }

scene_names, X_layers, y_text, metadata = load_dataset_from_pt_dir(PT_DIR)

le = LabelEncoder()
y = le.fit_transform(y_text)

train_idx, test_idx, train_scenes, test_scenes = split_by_scene(scene_names)

print("Number of samples:", len(scene_names))
print("Number of layers:", len(X_layers))
print("Classes:", list(le.classes_))

best_layer = None
best_f1 = -1

all_layer_results = []

for i, X in enumerate(X_layers):
    result = train_and_eval(
        X[train_idx], y[train_idx],
        X[test_idx], y[test_idx]
    )

    print(f"Layer {i:02d} | "
          f"Train Acc={result['train']['accuracy']:.3f} | "
          f"Test Acc={result['test']['accuracy']:.3f} | "
          f"F1={result['test']['macro_f1']:.3f}")

    if result["test"]["macro_f1"] > best_f1:
        best_f1 = result["test"]["macro_f1"]
        best_layer = i

    all_layer_results.append({
        "layer": i,
        "train": result["train"],
        "test": result["test"]
    })

print("\nBest layer:", best_layer)
print("Best F1:", best_f1)

output = {
    "best_layer": best_layer,
    "best_f1": best_f1,
    "results": all_layer_results,
    "classes": list(le.classes_)
}

with open(OUTPUT_JSON, "w") as f:
    json.dump(make_json_safe(output), f, indent=2)

print("Save completed:", OUTPUT_JSON)

from google.colab import files
files.download(OUTPUT_JSON)