# -*- coding: utf-8 -*-
"""linear_probe_pilot_2_scripts_step1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cgwp6by_1WHmQXINmifJeU2fR8pOogTK
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# set -e
# 
# apt-get update -y
# apt-get install -y xvfb x11-utils mesa-utils libgl1-mesa-glx libglib2.0-0
# pip -q install ai2thor tqdm

import os

os.makedirs("/content/pilot/scripts", exist_ok=True)
os.makedirs("/content/pilot/data", exist_ok=True)

config_text = r'''
import os

PILOT_DIR = os.path.dirname(os.path.abspath(__file__))

DATA_DIR = os.path.join(PILOT_DIR, "data")
STEP1_DIR = os.path.join(DATA_DIR, "step1_ground_truth")
STEP2_DIR = os.path.join(DATA_DIR, "step2_relations")
STEP3_DIR = os.path.join(DATA_DIR, "step3_text")

# pilot：2 scenes
SCENES = ["FloorPlan1", "FloorPlan2"]

MAX_OBJECTS_PER_SCENE = 12

USE_PICKUPABLE_ONLY = False

RANDOM_SEED = 42
'''

with open("/content/pilot/config.py", "w", encoding="utf-8") as f:
    f.write(config_text)

script_text = r'''
import json
import os
import random
import sys
from typing import Any, Dict, List, Set

from tqdm import tqdm
from ai2thor.controller import Controller


CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
PILOT_DIR = os.path.dirname(CURRENT_DIR)
PROJECT_ROOT = os.path.dirname(PILOT_DIR)

if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from pilot.config import (  # noqa: E402
    STEP1_DIR,
    SCENES,
    MAX_OBJECTS_PER_SCENE,
    USE_PICKUPABLE_ONLY,
    RANDOM_SEED,
)


random.seed(RANDOM_SEED)


def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def save_json(path: str, data: Any) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def get_position(obj: Dict[str, Any]) -> Dict[str, float]:
    pos = obj.get("position", {})
    return {
        "x": float(pos.get("x", 0.0)),
        "y": float(pos.get("y", 0.0)),
        "z": float(pos.get("z", 0.0)),
    }


def get_bbox(obj: Dict[str, Any]) -> Dict[str, Any]:

    # extract axis-aligned bounding box from AI2-THOR object metadata
        aabb = obj.get("axisAlignedBoundingBox", {}) or {}
    center = aabb.get("center", {}) or {}
    size = aabb.get("size", {}) or {}

    return {
        "center": {
            "x": float(center.get("x", 0.0)),
            "y": float(center.get("y", 0.0)),
            "z": float(center.get("z", 0.0)),
        },
        "size": {
            "x": float(size.get("x", 0.0)),
            "y": float(size.get("y", 0.0)),
            "z": float(size.get("z", 0.0)),
        },
        "cornerPoints": aabb.get("cornerPoints", []) or [],
    }


def get_rotation(obj: Dict[str, Any]) -> Dict[str, float]:
    
    # extract rotation from AI2-THOR object metadata
    rot = obj.get("rotation", {}) or {}
    return {
        "x": float(rot.get("x", 0.0)),
        "y": float(rot.get("y", 0.0)),
        "z": float(rot.get("z", 0.0)),
    }


def distance_2d(obj1: Dict[str, Any], obj2: Dict[str, Any]) -> float:

    # Compute the Euclidean distance between two objects in the x–z plane. 
    # This is used during sampling to retain locally spatially adjacent objects.

    p1 = get_position(obj1)
    p2 = get_position(obj2)

    return ((p1["x"] - p2["x"]) ** 2 + (p1["z"] - p2["z"]) ** 2) ** 0.5


def is_valid_object(obj: Dict[str, Any]) -> bool:
    
    # Filter out objects that are not suitable for the current pilot. 
    # A simple rule is used for now and can be extended in future iterations.
    if "objectType" not in obj or "position" not in obj:
        return False

    obj_type = obj.get("objectType", "")

    excluded_types = {"Floor", "Wall", "Room", "Ceiling"}
    if obj_type in excluded_types:
        return False

    if USE_PICKUPABLE_ONLY and not obj.get("pickupable", False):
        return False

    return True


def build_object_record(obj: Dict[str, Any]) -> Dict[str, Any]:

    # Construct a single object record
    return {
        "objectId": obj.get("objectId"),
        "objectType": obj.get("objectType"),
        "position": get_position(obj),
        "bbox": get_bbox(obj),
        "rotation": get_rotation(obj),
        "pickupable": bool(obj.get("pickupable", False)),
        "receptacle": bool(obj.get("receptacle", False)),
        "openable": bool(obj.get("openable", False)),
        "visible": bool(obj.get("visible", False)),
        "parentReceptacles": obj.get("parentReceptacles") or [],
        "receptacleObjectIds": obj.get("receptacleObjectIds") or [],
    }


def build_object_index(objects: List[Dict[str, Any]]) -> Dict[str, Dict[str, Any]]:

    # Build an index mapping objectId to object metadata
    return {
        obj["objectId"]: obj
        for obj in objects
        if obj.get("objectId") is not None
    }


def add_if_valid(
    obj: Dict[str, Any],
    selected: List[Dict[str, Any]],
    selected_ids: Set[str]
) -> bool:
    
    obj_id = obj.get("objectId")
    if obj_id is None:
        return False
    if obj_id in selected_ids:
        return False
    if not is_valid_object(obj):
        return False
    if len(selected) >= MAX_OBJECTS_PER_SCENE:
        return False

    selected.append(obj)
    selected_ids.add(obj_id)
    return True


def select_objects(raw_objects: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    
    # Relation-aware sampling strategy:
    # 1) First filter valid objects
    # 2) Randomly select a seed object
    # 3) Prioritize adding the seed’s parent receptacles
    # 4) If the seed is a receptacle, attempt to include a small number of contained objects
    # 5) Then prioritize adding objects near the seed to preserve local spatial structure
    # 6) If still insufficient, randomly fill the remaining slots
    #
    # This design preserves in/on relations required for Step 2,
    # while also providing a better object subset for subsequent geometric relations
    # (e.g., near / left_of / right_of, etc.).
    
    filtered = [obj for obj in raw_objects if is_valid_object(obj)]
    object_index = build_object_index(raw_objects)

    random.shuffle(filtered)

    selected: List[Dict[str, Any]] = []
    selected_ids: Set[str] = set()

    for seed in filtered:
        if len(selected) >= MAX_OBJECTS_PER_SCENE:
            break

        added_seed = add_if_valid(seed, selected, selected_ids)
        if not added_seed:
            continue

        parents = seed.get("parentReceptacles") or []
        for parent_id in parents:
            if len(selected) >= MAX_OBJECTS_PER_SCENE:
                break
            parent_obj = object_index.get(parent_id)
            if parent_obj is not None:
                add_if_valid(parent_obj, selected, selected_ids)

        if seed.get("receptacle", False):
            child_ids = seed.get("receptacleObjectIds") or []
            random.shuffle(child_ids)
            for child_id in child_ids[:2]:
                if len(selected) >= MAX_OBJECTS_PER_SCENE:
                    break
                child_obj = object_index.get(child_id)
                if child_obj is not None:
                    add_if_valid(child_obj, selected, selected_ids)

        if len(selected) < MAX_OBJECTS_PER_SCENE:
            nearby_candidates = [
                obj for obj in filtered
                if obj.get("objectId") not in selected_ids
            ]
            nearby_candidates.sort(key=lambda obj: distance_2d(seed, obj))

            for obj in nearby_candidates[:3]:
                if len(selected) >= MAX_OBJECTS_PER_SCENE:
                    break
                add_if_valid(obj, selected, selected_ids)

    if len(selected) < MAX_OBJECTS_PER_SCENE:
        leftovers = [obj for obj in filtered if obj.get("objectId") not in selected_ids]
        random.shuffle(leftovers)
        for obj in leftovers:
            if len(selected) >= MAX_OBJECTS_PER_SCENE:
                break
            add_if_valid(obj, selected, selected_ids)

    return selected


def extract_scene_ground_truth(controller: Controller, scene: str) -> Dict[str, Any]:

    event = controller.reset(scene=scene)
    metadata = event.metadata

    raw_objects = metadata.get("objects", [])
    selected_objects = select_objects(raw_objects)
    object_records = [build_object_record(obj) for obj in selected_objects]

    return {
        "scene": scene,
        "num_all_objects": len(raw_objects),
        "num_selected_objects": len(object_records),
        "objects": object_records,
    }


def main() -> None:
    ensure_dir(STEP1_DIR)

    print("Starting Step1: Spatial Ground Truth Construction", flush=True)
    print(f"Scenes: {SCENES}", flush=True)
    print(f"Output dir: {STEP1_DIR}", flush=True)
    print(f"Max objects per scene: {MAX_OBJECTS_PER_SCENE}", flush=True)
    print(f"USE_PICKUPABLE_ONLY: {USE_PICKUPABLE_ONLY}", flush=True)

    controller = None
    try:
        controller = Controller(
            scene=SCENES[0],
            width=300,
            height=300,
            agentMode="default",
        )

        for scene in tqdm(SCENES, desc="Extracting scenes"):
            scene_data = extract_scene_ground_truth(controller, scene)
            out_path = os.path.join(STEP1_DIR, f"{scene}.json")
            save_json(out_path, scene_data)
            print(
                f"Saved {scene}: "
                f"{scene_data['num_selected_objects']} / {scene_data['num_all_objects']} objects",
                flush=True,
            )

        print("Step1 completed.", flush=True)

    finally:
        if controller is not None:
            controller.stop()


if __name__ == "__main__":
    main()
'''

with open("/content/pilot/scripts/step1_extract_ground_truth.py", "w", encoding="utf-8") as f:
    f.write(script_text)

print("Updated step1_extract_ground_truth.py written successfully.")

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# set -e
# 
# xvfb-run -s "-screen 0 1024x768x24" \
# env LIBGL_ALWAYS_SOFTWARE=1 \
# python /content/pilot/scripts/step1_extract_ground_truth.py

!find /content/pilot/data/step1_ground_truth -maxdepth 2 -type f

!zip -r /content/step1_ground_truth.zip /content/pilot/data/step1_ground_truth

from google.colab import files
files.download('/content/step1_ground_truth.zip')

import json
from pprint import pprint

path = "/content/pilot/data/step1_ground_truth/FloorPlan1.json"

with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

print("=== Top level keys ===")
print(data.keys())

print("\nScene:", data["scene"])
print("Num all objects:", data["num_all_objects"])
print("Num selected objects:", data["num_selected_objects"])

print("\n=== One object example ===")
pprint(data["objects"][0])

import json

with open('/content/pilot/data/step1_ground_truth/FloorPlan1.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

for i, obj in enumerate(data["objects"]):
    print(i, obj["objectType"], "| receptacle =", obj["receptacle"], "| parents =", obj["parentReceptacles"])

import json

with open('/content/pilot/data/step1_ground_truth/FloorPlan1.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

selected_ids = {obj["objectId"] for obj in data["objects"]}

print("=== parent membership check ===")
for obj in data["objects"]:
    for p in obj["parentReceptacles"]:
        print(
            f'{obj["objectType"]} | parent = {p} | in_selected = {p in selected_ids}'
        )