# -*- coding: utf-8 -*-
"""linear_probe_pilot_2_scripts_step1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cgwp6by_1WHmQXINmifJeU2fR8pOogTK
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# set -e
# 
# apt-get update -y
# apt-get install -y xvfb x11-utils mesa-utils libgl1-mesa-glx libglib2.0-0
# pip -q install ai2thor tqdm

import os

os.makedirs("/content/pilot/scripts", exist_ok=True)
os.makedirs("/content/pilot/data", exist_ok=True)

config_text = r'''
import os

# pilot/ 目录
PILOT_DIR = os.path.dirname(os.path.abspath(__file__))

# 数据目录
DATA_DIR = os.path.join(PILOT_DIR, "data")
STEP1_DIR = os.path.join(DATA_DIR, "step1_ground_truth")
STEP2_DIR = os.path.join(DATA_DIR, "step2_relations")
STEP3_DIR = os.path.join(DATA_DIR, "step3_text")

# 小规模 pilot：先只跑两个场景
SCENES = ["FloorPlan1", "FloorPlan2"]

# 每个场景最多保留多少对象
MAX_OBJECTS_PER_SCENE = 12

# 是否只保留 pickupable 物体
USE_PICKUPABLE_ONLY = False

# 随机种子
RANDOM_SEED = 42
'''

with open("/content/pilot/config.py", "w", encoding="utf-8") as f:
    f.write(config_text)

script_text = r'''
import json
import os
import random
import sys
from typing import Any, Dict, List, Set

from tqdm import tqdm
from ai2thor.controller import Controller


# 让脚本能找到 pilot/config.py
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
PILOT_DIR = os.path.dirname(CURRENT_DIR)
PROJECT_ROOT = os.path.dirname(PILOT_DIR)

if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from pilot.config import (  # noqa: E402
    STEP1_DIR,
    SCENES,
    MAX_OBJECTS_PER_SCENE,
    USE_PICKUPABLE_ONLY,
    RANDOM_SEED,
)


random.seed(RANDOM_SEED)


def ensure_dir(path: str) -> None:
    """如果目录不存在则创建。"""
    os.makedirs(path, exist_ok=True)


def save_json(path: str, data: Any) -> None:
    """保存 JSON 文件。"""
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def get_position(obj: Dict[str, Any]) -> Dict[str, float]:
    """从 AI2-THOR object metadata 中提取 position。"""
    pos = obj.get("position", {})
    return {
        "x": float(pos.get("x", 0.0)),
        "y": float(pos.get("y", 0.0)),
        "z": float(pos.get("z", 0.0)),
    }


def get_bbox(obj: Dict[str, Any]) -> Dict[str, Any]:
    """
    从 AI2-THOR object metadata 中提取 axis-aligned bounding box。
    为后续 Step2 的几何关系（left/right/above/near 等）提供基础。
    """
    aabb = obj.get("axisAlignedBoundingBox", {}) or {}
    center = aabb.get("center", {}) or {}
    size = aabb.get("size", {}) or {}

    return {
        "center": {
            "x": float(center.get("x", 0.0)),
            "y": float(center.get("y", 0.0)),
            "z": float(center.get("z", 0.0)),
        },
        "size": {
            "x": float(size.get("x", 0.0)),
            "y": float(size.get("y", 0.0)),
            "z": float(size.get("z", 0.0)),
        },
        "cornerPoints": aabb.get("cornerPoints", []) or [],
    }


def get_rotation(obj: Dict[str, Any]) -> Dict[str, float]:
    """
    从 AI2-THOR object metadata 中提取 rotation。
    当前 Step2 第一版可能还不直接用，但建议在 Step1 就保留下来。
    """
    rot = obj.get("rotation", {}) or {}
    return {
        "x": float(rot.get("x", 0.0)),
        "y": float(rot.get("y", 0.0)),
        "z": float(rot.get("z", 0.0)),
    }


def distance_2d(obj1: Dict[str, Any], obj2: Dict[str, Any]) -> float:
    """
    计算两个对象在 x-z 平面上的欧氏距离。
    用于在 Step1 抽样时保留局部空间邻近对象。
    """
    p1 = get_position(obj1)
    p2 = get_position(obj2)

    return ((p1["x"] - p2["x"]) ** 2 + (p1["z"] - p2["z"]) ** 2) ** 0.5


def is_valid_object(obj: Dict[str, Any]) -> bool:
    """
    过滤不适合当前 pilot 的对象。
    当前仍保持较简单规则，但为后续扩展预留更清晰的结构。
    """
    if "objectType" not in obj or "position" not in obj:
        return False

    obj_type = obj.get("objectType", "")

    excluded_types = {"Floor", "Wall", "Room", "Ceiling"}
    if obj_type in excluded_types:
        return False

    if USE_PICKUPABLE_ONLY and not obj.get("pickupable", False):
        return False

    return True


def build_object_record(obj: Dict[str, Any]) -> Dict[str, Any]:
    """
    构造 Step1 输出中的单个 object record。
    相比旧版本，新增了 bbox 和 rotation，
    使输出能够支持后续 Step2 的几何关系构造。
    """
    return {
        "objectId": obj.get("objectId"),
        "objectType": obj.get("objectType"),
        "position": get_position(obj),
        "bbox": get_bbox(obj),
        "rotation": get_rotation(obj),
        "pickupable": bool(obj.get("pickupable", False)),
        "receptacle": bool(obj.get("receptacle", False)),
        "openable": bool(obj.get("openable", False)),
        "visible": bool(obj.get("visible", False)),
        "parentReceptacles": obj.get("parentReceptacles") or [],
        "receptacleObjectIds": obj.get("receptacleObjectIds") or [],
    }


def build_object_index(objects: List[Dict[str, Any]]) -> Dict[str, Dict[str, Any]]:
    """建立 objectId -> object metadata 的索引。"""
    return {
        obj["objectId"]: obj
        for obj in objects
        if obj.get("objectId") is not None
    }


def add_if_valid(
    obj: Dict[str, Any],
    selected: List[Dict[str, Any]],
    selected_ids: Set[str]
) -> bool:
    """
    如果对象合法且未被选中，则加入 selected。
    返回是否成功加入。
    """
    obj_id = obj.get("objectId")
    if obj_id is None:
        return False
    if obj_id in selected_ids:
        return False
    if not is_valid_object(obj):
        return False
    if len(selected) >= MAX_OBJECTS_PER_SCENE:
        return False

    selected.append(obj)
    selected_ids.add(obj_id)
    return True


def select_objects(raw_objects: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    升级版关系友好型抽样：
    1) 先过滤合法对象
    2) 随机选 seed object
    3) 优先加入 seed 的 parent receptacles
    4) 如果 seed 是 receptacle，尝试加入少量 contained objects
    5) 再优先加入 seed 附近的对象，保留局部空间结构
    6) 若仍不足，再随机补齐

    这样既能保留 Step2 当前需要的 in/on 关系，
    也能为后续几何关系（near / left_of / right_of 等）提供更好的对象子集。
    """
    filtered = [obj for obj in raw_objects if is_valid_object(obj)]
    object_index = build_object_index(raw_objects)

    random.shuffle(filtered)

    selected: List[Dict[str, Any]] = []
    selected_ids: Set[str] = set()

    for seed in filtered:
        if len(selected) >= MAX_OBJECTS_PER_SCENE:
            break

        # 1) 先加 seed 自己
        added_seed = add_if_valid(seed, selected, selected_ids)
        if not added_seed:
            continue

        # 2) 再尽量加入 seed 的父容器
        parents = seed.get("parentReceptacles") or []
        for parent_id in parents:
            if len(selected) >= MAX_OBJECTS_PER_SCENE:
                break
            parent_obj = object_index.get(parent_id)
            if parent_obj is not None:
                add_if_valid(parent_obj, selected, selected_ids)

        # 3) 如果 seed 是 receptacle，尝试加入其内部对象（少量）
        if seed.get("receptacle", False):
            child_ids = seed.get("receptacleObjectIds") or []
            random.shuffle(child_ids)
            for child_id in child_ids[:2]:
                if len(selected) >= MAX_OBJECTS_PER_SCENE:
                    break
                child_obj = object_index.get(child_id)
                if child_obj is not None:
                    add_if_valid(child_obj, selected, selected_ids)

        # 4) 优先加入 seed 附近的对象，保留局部空间邻近关系
        if len(selected) < MAX_OBJECTS_PER_SCENE:
            nearby_candidates = [
                obj for obj in filtered
                if obj.get("objectId") not in selected_ids
            ]
            nearby_candidates.sort(key=lambda obj: distance_2d(seed, obj))

            for obj in nearby_candidates[:3]:
                if len(selected) >= MAX_OBJECTS_PER_SCENE:
                    break
                add_if_valid(obj, selected, selected_ids)

    # 5) 如果还没满，再随机补齐
    if len(selected) < MAX_OBJECTS_PER_SCENE:
        leftovers = [obj for obj in filtered if obj.get("objectId") not in selected_ids]
        random.shuffle(leftovers)
        for obj in leftovers:
            if len(selected) >= MAX_OBJECTS_PER_SCENE:
                break
            add_if_valid(obj, selected, selected_ids)

    return selected


def extract_scene_ground_truth(controller: Controller, scene: str) -> Dict[str, Any]:
    """
    对单个 scene 执行 Step1：
    reset scene -> 读取 metadata -> 保留少量对象 -> 生成 JSON 结构
    """
    event = controller.reset(scene=scene)
    metadata = event.metadata

    raw_objects = metadata.get("objects", [])
    selected_objects = select_objects(raw_objects)
    object_records = [build_object_record(obj) for obj in selected_objects]

    return {
        "scene": scene,
        "num_all_objects": len(raw_objects),
        "num_selected_objects": len(object_records),
        "objects": object_records,
    }


def main() -> None:
    ensure_dir(STEP1_DIR)

    print("Starting Step1: Spatial Ground Truth Construction", flush=True)
    print(f"Scenes: {SCENES}", flush=True)
    print(f"Output dir: {STEP1_DIR}", flush=True)
    print(f"Max objects per scene: {MAX_OBJECTS_PER_SCENE}", flush=True)
    print(f"USE_PICKUPABLE_ONLY: {USE_PICKUPABLE_ONLY}", flush=True)

    controller = None
    try:
        controller = Controller(
            scene=SCENES[0],
            width=300,
            height=300,
            agentMode="default",
        )

        for scene in tqdm(SCENES, desc="Extracting scenes"):
            scene_data = extract_scene_ground_truth(controller, scene)
            out_path = os.path.join(STEP1_DIR, f"{scene}.json")
            save_json(out_path, scene_data)
            print(
                f"Saved {scene}: "
                f"{scene_data['num_selected_objects']} / {scene_data['num_all_objects']} objects",
                flush=True,
            )

        print("Step1 completed.", flush=True)

    finally:
        if controller is not None:
            controller.stop()


if __name__ == "__main__":
    main()
'''

with open("/content/pilot/scripts/step1_extract_ground_truth.py", "w", encoding="utf-8") as f:
    f.write(script_text)

print("Updated step1_extract_ground_truth.py written successfully.")

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# set -e
# 
# xvfb-run -s "-screen 0 1024x768x24" \
# env LIBGL_ALWAYS_SOFTWARE=1 \
# python /content/pilot/scripts/step1_extract_ground_truth.py

!find /content/pilot/data/step1_ground_truth -maxdepth 2 -type f

!zip -r /content/step1_ground_truth.zip /content/pilot/data/step1_ground_truth

from google.colab import files
files.download('/content/step1_ground_truth.zip')

import json
from pprint import pprint

path = "/content/pilot/data/step1_ground_truth/FloorPlan1.json"

with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

print("=== Top level keys ===")
print(data.keys())

print("\nScene:", data["scene"])
print("Num all objects:", data["num_all_objects"])
print("Num selected objects:", data["num_selected_objects"])

print("\n=== One object example ===")
pprint(data["objects"][0])

import json

with open('/content/pilot/data/step1_ground_truth/FloorPlan1.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

for i, obj in enumerate(data["objects"]):
    print(i, obj["objectType"], "| receptacle =", obj["receptacle"], "| parents =", obj["parentReceptacles"])

import json

with open('/content/pilot/data/step1_ground_truth/FloorPlan1.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

selected_ids = {obj["objectId"] for obj in data["objects"]}

print("=== parent membership check ===")
for obj in data["objects"]:
    for p in obj["parentReceptacles"]:
        print(
            f'{obj["objectType"]} | parent = {p} | in_selected = {p in selected_ids}'
        )