# -*- coding: utf-8 -*-
"""pilot2_step3_4_generate_paragraph_with_OLMo2_long_prompt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OfLnwP8b0k0md_bKoYEKz0NxudUorV5o
"""

# =========================================================
# 0. Upload step2_relations.zip
# =========================================================

from google.colab import files
import os
import shutil
import zipfile

uploaded = files.upload()
uploaded_files = list(uploaded.keys())

if not uploaded_files:
    raise FileNotFoundError("No file was uploaded.")

print("Uploaded files:", uploaded_files)

if len(uploaded_files) != 1:
    raise ValueError(f"Please upload exactly one zip file, got: {uploaded_files}")

uploaded_name = uploaded_files[0]
zip_path = f"/content/{uploaded_name}"

print("Using uploaded zip file:", zip_path)


# =========================================================
# 1. Prepare local directories
# =========================================================

LOCAL_BASE = "/content/linear_probe/pilot_2"
LOCAL_DATA_DIR = f"{LOCAL_BASE}/data"
LOCAL_INPUT_DIR = f"{LOCAL_DATA_DIR}/step2_relations"
LOCAL_OUTPUT_DIR = "/content/step3_4_long_prompt_FloorPlan1_olmo2_generated_paragraph"

os.makedirs(LOCAL_DATA_DIR, exist_ok=True)
os.makedirs(LOCAL_OUTPUT_DIR, exist_ok=True)

if not os.path.isfile(zip_path):
    raise FileNotFoundError(f"Uploaded zip file not found: {zip_path}")

# clean old input dir
if os.path.exists(LOCAL_INPUT_DIR):
    shutil.rmtree(LOCAL_INPUT_DIR)

extract_tmp = f"{LOCAL_DATA_DIR}/_extract_tmp"
if os.path.exists(extract_tmp):
    shutil.rmtree(extract_tmp)
os.makedirs(extract_tmp, exist_ok=True)

with zipfile.ZipFile(zip_path, "r") as zf:
    zf.extractall(extract_tmp)

# compatible with:
# 1) zip directly contains json files
# 2) zip contains an outer folder step2_relations
entries = os.listdir(extract_tmp)

if len(entries) == 1 and os.path.isdir(os.path.join(extract_tmp, entries[0])):
    inner_dir = os.path.join(extract_tmp, entries[0])
    shutil.move(inner_dir, LOCAL_INPUT_DIR)
else:
    os.makedirs(LOCAL_INPUT_DIR, exist_ok=True)
    for name in entries:
        shutil.move(os.path.join(extract_tmp, name), os.path.join(LOCAL_INPUT_DIR, name))

shutil.rmtree(extract_tmp)

print("Prepared input dir:", LOCAL_INPUT_DIR)
print("Input dir preview:", os.listdir(LOCAL_INPUT_DIR)[:10])

# =========================================================
# 1. Environment and dependencies
# =========================================================

import os

os.environ["HF_HOME"] = "/content/hf_cache"
os.environ["TRANSFORMERS_CACHE"] = "/content/hf_cache"
os.environ["PIP_CACHE_DIR"] = "/content/pip_cache"

print("HF_HOME =", os.environ["HF_HOME"])
print("TRANSFORMERS_CACHE =", os.environ["TRANSFORMERS_CACHE"])
print("PIP_CACHE_DIR =", os.environ["PIP_CACHE_DIR"])

print("\nDisk usage:")
!df -h /content

!pip install -q --no-cache-dir transformers accelerate sentencepiece safetensors
!pip install -q bitsandbytes

import torch

print("torch.cuda.is_available() =", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU count =", torch.cuda.device_count())
    print("GPU name  =", torch.cuda.get_device_name(0))
else:
    print("No GPU available. 7B inference on CPU will be very slow.")

!nvidia-smi

# =========================================================
# 2. Config
# =========================================================

INPUT_DIR = "/content/linear_probe/pilot_2/data/step2_relations"
OUTPUT_DIR = "/content/step3_4_long_prompt_FloorPlan1_olmo2_generated_paragraph"
HF_CACHE_DIR = "/content/hf_cache"

print("INPUT_DIR =", INPUT_DIR)
print("OUTPUT_DIR =", OUTPUT_DIR)
print("HF_CACHE_DIR =", HF_CACHE_DIR)

# =========================================================
# 3. Main code
# =========================================================

import json
import os
import re
import time
from pathlib import Path
from typing import Dict, List, Any
from collections import defaultdict

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

# =========================
# User-configurable settings
# =========================

MODEL_NAME = "allenai/OLMo-2-1124-7B-Instruct"

INPUT_DIR = "/content/linear_probe/pilot_2/data/step2_relations"
OUTPUT_DIR = "/content/step3_4_long_prompt_FloorPlan1_olmo2_generated_paragraph"
HF_CACHE_DIR = "/content/hf_cache"

USE_4BIT = True

MAX_NEW_TOKENS = 320
MAX_WORDS_PER_PARAGRAPH = 220

# 每批最多多少条 relations
MAX_RELATIONS_PER_BATCH = 8

DO_SAMPLE = False
TEMPERATURE = 0.3
TOP_P = 0.9

OVERWRITE = True

# =========================
# Utility helpers
# =========================

def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def load_json(path: str) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def save_json(path: str, data: Dict[str, Any]) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def normalize_text(text: str) -> str:
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def extract_assistant_text(generated_text: str) -> str:
    text = generated_text.strip()

    prefixes = [
        "assistant\n",
        "assistant:",
        "Assistant:",
        "Paragraph:",
        "Output:",
        "Generated paragraph:",
        "Result:",
    ]
    for p in prefixes:
        if text.startswith(p):
            text = text[len(p):].strip()

    text = text.strip("`").strip()
    return text


def count_words(text: str) -> int:
    return len(re.findall(r"\b\w+\b", text))


def split_into_sentences_for_trim(text: str) -> List[str]:
    text = normalize_text(text)
    if not text:
        return []
    parts = re.split(r'(?<=[.!?])\s+', text)
    return [p.strip() for p in parts if p.strip()]


def trim_to_word_limit_keep_full_sentences(text: str, max_words: int) -> str:
    sentences = split_into_sentences_for_trim(text)
    if not sentences:
        return ""

    kept = []
    total = 0

    for sent in sentences:
        sent_words = count_words(sent)
        if total + sent_words <= max_words:
            kept.append(sent)
            total += sent_words
        else:
            break

    if kept:
        return " ".join(kept).strip()

    words = re.findall(r"\S+", text)
    return " ".join(words[:max_words]).strip()


def normalize_object_type(obj_type: str) -> str:
    """
    Convert AI2-THOR objectType to a more natural English phrase.
    Example: CoffeeMachine -> coffee machine
    """
    if not obj_type:
        return ""

    chars = []
    for i, ch in enumerate(obj_type):
        if i > 0 and ch.isupper() and obj_type[i - 1].islower():
            chars.append(" ")
        chars.append(ch)

    return "".join(chars).strip().lower()


def should_use_relation_for_text(rel: Dict[str, Any]) -> bool:
    """
    Keep relations that are marked as verbalizable / candidate_for_text.
    """
    if not rel.get("candidate_for_text", True):
        return False
    if not rel.get("verbalizable", True):
        return False
    return True


def build_entity_alias_map(relations: List[Dict[str, Any]]) -> Dict[str, str]:
    """
    Build a scene-level alias map:
    full object id -> unique readable alias

    Example:
    Drawer|+00.95|+00.83|-02.20 -> drawer_1
    Drawer|+00.95|+00.56|-02.20 -> drawer_2

    This follows the same item-level idea as your uploaded step3/step4 scripts:
    use full IDs as unique keys, then expose readable aliases in text/prompt.
    """
    ids_by_type = defaultdict(set)

    for rel in relations:
        subject_id = rel["subject_id"]
        subject_type = rel["subject_type"]
        object_id = rel["object_id"]
        object_type = rel["object_type"]

        ids_by_type[subject_type].add(subject_id)
        ids_by_type[object_type].add(object_id)

    alias_map: Dict[str, str] = {}

    for obj_type, full_ids in ids_by_type.items():
        base = normalize_object_type(obj_type).replace(" ", "_")
        for idx, full_id in enumerate(sorted(full_ids), start=1):
            alias_map[full_id] = f"{base}_{idx}"

    return alias_map


def relation_to_fact(rel: Dict[str, Any], alias_map: Dict[str, str]) -> str:
    """
    Convert one structured relation into a controlled fact string.
    Use item-level aliases to distinguish different physical instances.
    """
    subject_alias = alias_map[rel["subject_id"]]
    object_alias = alias_map[rel["object_id"]]
    relation = rel["relation"]

    return f"({subject_alias}, {relation}, {object_alias})"


def build_fact_list(relations: List[Dict[str, Any]], alias_map: Dict[str, str]) -> str:
    facts = []
    for i, rel in enumerate(relations, start=1):
        facts.append(f"{i}. {relation_to_fact(rel, alias_map)}")
    return "\n".join(facts)


def chunk_scene_relations(scene_data: Dict[str, Any], max_relations_per_batch: int) -> List[Dict[str, Any]]:
    """
    Split one scene into multiple batches by number of relations.
    Keep a scene-level alias map so same-type objects are distinguishable.
    """
    scene = scene_data.get("scene", "UNKNOWN_SCENE")
    all_relations = scene_data.get("relations", []) or []

    selected_relations = [
        rel for rel in all_relations
        if should_use_relation_for_text(rel)
    ]

    alias_map = build_entity_alias_map(selected_relations)

    if not selected_relations:
        return [{
            "scene": scene,
            "relations": [],
            "num_relations": 0,
            "chunk_id": 1,
            "num_chunks": 1,
            "entity_alias_map": {},
        }]

    chunks = []
    total_chunks = (len(selected_relations) + max_relations_per_batch - 1) // max_relations_per_batch

    for i in range(0, len(selected_relations), max_relations_per_batch):
        batch_relations = selected_relations[i:i + max_relations_per_batch]
        chunk_id = len(chunks) + 1

        used_ids = set()
        for rel in batch_relations:
            used_ids.add(rel["subject_id"])
            used_ids.add(rel["object_id"])

        batch_alias_map = {
            obj_id: alias
            for obj_id, alias in alias_map.items()
            if obj_id in used_ids
        }

        chunks.append({
            "scene": scene,
            "relations": batch_relations,
            "num_relations": len(batch_relations),
            "chunk_id": chunk_id,
            "num_chunks": total_chunks,
            "entity_alias_map": batch_alias_map,
        })

    return chunks


def build_prompt(scene_batch: Dict[str, Any]) -> List[Dict[str, str]]:
    scene = scene_batch.get("scene", "UNKNOWN_SCENE")
    relations = scene_batch.get("relations", [])
    chunk_id = scene_batch.get("chunk_id", 1)
    num_chunks = scene_batch.get("num_chunks", 1)
    alias_map = scene_batch.get("entity_alias_map", {}) or {}

    fact_list = build_fact_list(relations, alias_map)

    # Only expose aliases, never raw object IDs with coordinates.
    alias_names = sorted(alias_map.values())

    # Group aliases by base object type, e.g. drawer -> [drawer_1, drawer_2]
    grouped_aliases = defaultdict(list)
    for alias in alias_names:
        m = re.match(r"^(.*)_(\d+)$", alias)
        if m:
            base = m.group(1)
        else:
            base = alias
        grouped_aliases[base].append(alias)

    identity_rule_lines = []
    for base in sorted(grouped_aliases.keys()):
        aliases = sorted(grouped_aliases[base])
        if len(aliases) == 1:
            identity_rule_lines.append(
                f"- {aliases[0]} is a distinct object instance. Use this alias exactly."
            )
        else:
            alias_str = ", ".join(aliases)
            identity_rule_lines.append(
                f"- {alias_str} are different physical instances of the same object type. "
                f"Do not merge them. Use each alias exactly as written."
            )

    identity_rules_text = "\n".join(identity_rule_lines).strip()
    alias_list_text = ", ".join(alias_names) if alias_names else "None"

    system_prompt = (
        "You are a careful assistant for generating spatial scene descriptions.\n"
        "Your task is to convert structured spatial relations into one simple English paragraph.\n"
        "You must preserve the spatial meaning exactly.\n"
        "Object aliases such as drawer_1 and drawer_2 refer to different physical instances and must never be merged.\n"
        "Never output raw object IDs, coordinates, or strings containing vertical bars like Object|x|y|z."
    )

    user_prompt = f"""
Scene: {scene}
Batch: {chunk_id}/{num_chunks}

Task:
Write ONE English paragraph based only on the input spatial relations.

Goal:
Produce a simple, literal, and accurate paragraph.
The paragraph must preserve the spatial relations exactly.
Do not add interpretation or scene-level summary.

Allowed object names:
{alias_list_text}

Object identity rules:
{identity_rules_text if identity_rules_text else "None provided."}

Guidelines:

1. COVER ALL RELATIONS
- Every distinct input relation must appear at least once in the output.
- Do not omit any distinct relation.

2. PRESERVE SPATIAL MEANING
- Keep every subject, relation, and object correct.
- You may use an equivalent inverse form only if the meaning stays exactly the same.
  Example: "drawer_1 is below fork_1" ↔ "fork_1 is above drawer_1"

3. DO NOT WEAKEN RELATIONS
- Do not replace precise relations with vague ones.
- Keep the original relation meaning as close as possible.

Forbidden examples:
- left_of -> near / beside / next to
- right_of -> near / beside / next to
- above -> over / on top of
- near -> close to / adjacent to

4. DO NOT ADD NEW RELATIONS
- Do not infer extra relations.
- Do not combine facts in a way that creates new meaning.

5. DO NOT ADD NEW OBJECTS
- Only mention objects that appear in the input facts.

6. DO NOT MERGE OBJECT INSTANCES
- Different aliases always refer to different physical objects.
- Never merge drawer_1 and drawer_2 into one drawer.
- Never treat cabinet_1 and cabinet_2 as the same object.

7. KEEP OBJECT NAMES EXACT
- Preserve aliases exactly, including suffixes like _1, _2, _3.
- Do not rename, simplify, paraphrase, or remove numeric suffixes.
- Do not change "wine_bottle_1" to "wine bottle 1".
- Do not change "drawer_2" to "the drawer".

8. NEVER OUTPUT RAW IDS OR COORDINATES
- Do not output original object IDs.
- Do not output coordinates.
- Do not output strings like "Drawer|+00.95|+00.83|-02.20".
- Use only the allowed object names listed above.

9. USE SIMPLE AND LITERAL LANGUAGE
- Use direct sentence structures.
- Avoid narrative or interpretive wording.

10. STRUCTURE
- Write exactly ONE paragraph.
- Slight repetition is acceptable.
- Correctness is more important than fluency.

11. STOP AFTER THE FACTS
- Do not continue with general scene description.

Output:
Return exactly one paragraph. No explanations.

Input spatial relations:
{fact_list}
""".strip()

    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]


def load_model_and_tokenizer(model_name: str, use_4bit: bool = False):
    tokenizer = AutoTokenizer.from_pretrained(
        model_name,
        trust_remote_code=True,
        cache_dir=HF_CACHE_DIR,
    )

    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model_kwargs = {
        "trust_remote_code": True,
        "device_map": "auto",
        "cache_dir": HF_CACHE_DIR,
    }

    if use_4bit:
        from transformers import BitsAndBytesConfig

        compute_dtype = torch.bfloat16 if torch.cuda.is_available() else torch.float32

        model_kwargs["quantization_config"] = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=compute_dtype,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type="nf4",
        )
    else:
        model_kwargs["torch_dtype"] = torch.bfloat16 if torch.cuda.is_available() else torch.float32

    model = AutoModelForCausalLM.from_pretrained(model_name, **model_kwargs)
    model.eval()
    return tokenizer, model


@torch.no_grad()
def generate_paragraph(
    tokenizer,
    model,
    scene_batch: Dict[str, Any],
    max_new_tokens: int = 320,
    do_sample: bool = False,
    temperature: float = 0.3,
    top_p: float = 0.9,
    max_words_per_paragraph: int = 220,
) -> Dict[str, Any]:
    messages = build_prompt(scene_batch)

    if hasattr(tokenizer, "apply_chat_template"):
        prompt_text = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
        )
    else:
        prompt_text = (
            f"System: {messages[0]['content']}\n\n"
            f"User: {messages[1]['content']}\n\n"
            f"Assistant:"
        )

    inputs = tokenizer(
        prompt_text,
        return_tensors="pt",
        truncation=True,
    )
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    generation_kwargs = {
        "max_new_tokens": max_new_tokens,
        "do_sample": do_sample,
        "pad_token_id": tokenizer.pad_token_id,
        "eos_token_id": tokenizer.eos_token_id,
    }

    if do_sample:
        generation_kwargs["temperature"] = temperature
        generation_kwargs["top_p"] = top_p

    output_ids = model.generate(**inputs, **generation_kwargs)

    prompt_len = inputs["input_ids"].shape[1]
    new_tokens = output_ids[0][prompt_len:]
    decoded = tokenizer.decode(new_tokens, skip_special_tokens=True)
    generated_raw = normalize_text(extract_assistant_text(decoded))
    generated_trimmed = trim_to_word_limit_keep_full_sentences(
        generated_raw,
        max_words=max_words_per_paragraph,
    )

    return {
        "prompt_text": prompt_text,
        "generated_paragraph_raw": generated_raw,
        "generated_paragraph": generated_trimmed,
        "generated_word_count_raw": count_words(generated_raw),
        "generated_word_count_final": count_words(generated_trimmed),
    }


def build_output_record(
    scene_data: Dict[str, Any],
    selected_relations: List[Dict[str, Any]],
    generation_results: List[Dict[str, Any]],
    entity_alias_map: Dict[str, str],
) -> Dict[str, Any]:
    generated_paragraphs = [x["generated_paragraph"] for x in generation_results]
    generated_paragraphs_raw = [x["generated_paragraph_raw"] for x in generation_results]

    return {
        "scene": scene_data.get("scene"),
        "model_family": "OLMo",
        "model_name": MODEL_NAME,
        "input_num_relations_total": len(scene_data.get("relations", [])),
        "input_num_relations_selected": len(selected_relations),
        "input_relations_selected": selected_relations,
        "input_entity_alias_map": entity_alias_map,

        "generated_paragraphs": generated_paragraphs,
        "generated_paragraph": "\n\n".join(generated_paragraphs),

        "metadata": {
            "max_new_tokens": MAX_NEW_TOKENS,
            "max_words_per_paragraph": MAX_WORDS_PER_PARAGRAPH,
            "max_relations_per_batch": MAX_RELATIONS_PER_BATCH,
            "do_sample": DO_SAMPLE,
            "temperature": TEMPERATURE if DO_SAMPLE else None,
            "top_p": TOP_P if DO_SAMPLE else None,
            "num_output_paragraphs": len(generated_paragraphs),
            "raw_word_counts": [x["generated_word_count_raw"] for x in generation_results],
            "final_word_counts": [x["generated_word_count_final"] for x in generation_results],
            "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        },

        "generated_paragraphs_raw": generated_paragraphs_raw,
    }


def process_file(
    input_path: Path,
    output_dir: Path,
    tokenizer,
    model,
) -> None:
    scene_data = load_json(str(input_path))
    scene_name = scene_data.get("scene", input_path.stem)

    output_filename = f"{scene_name}_olmo2_generated_text.json"
    output_path = output_dir / output_filename

    if output_path.exists() and not OVERWRITE:
        print(f"[Skip] {output_filename} already exists.")
        return

    print(f"[Run ] Processing {input_path.name} ...")

    all_relations = scene_data.get("relations", [])
    selected_relations = [
    rel for rel in all_relations
    if should_use_relation_for_text(rel)
    ]

    entity_alias_map = build_entity_alias_map(selected_relations)

    batches = chunk_scene_relations(
        scene_data=scene_data,
        max_relations_per_batch=MAX_RELATIONS_PER_BATCH,
    )

    generation_results = []

    for batch in batches:
        chunk_id = batch.get("chunk_id", 1)
        num_chunks = batch.get("num_chunks", 1)

        print(f"  [Batch {chunk_id}/{num_chunks}] Generating...")

        result = generate_paragraph(
            tokenizer=tokenizer,
            model=model,
            scene_batch=batch,
            max_new_tokens=MAX_NEW_TOKENS,
            do_sample=DO_SAMPLE,
            temperature=TEMPERATURE,
            top_p=TOP_P,
            max_words_per_paragraph=MAX_WORDS_PER_PARAGRAPH,
        )

        generation_results.append(result)

        print(
            f"  [Batch {chunk_id}/{num_chunks}] Done. "
            f"final_words={result['generated_word_count_final']}"
        )

    out_data = build_output_record(
        scene_data=scene_data,
        selected_relations=selected_relations,
        generation_results=generation_results,
        entity_alias_map=entity_alias_map,
    )
    save_json(str(output_path), out_data)

    print(f"[Done] Saved to {output_path}")

# =========================
# Split execution helpers
# =========================

def prepare_inference():
    input_dir = Path(INPUT_DIR)
    output_dir = Path(OUTPUT_DIR)

    ensure_dir(str(output_dir))

    input_files = sorted(input_dir.glob("*_relations.json"))
    if not input_files:
        raise FileNotFoundError(f"No *_relations.json files found in: {input_dir}")

    print("=" * 80)
    print("Preparing inference...")
    print(f"MODEL_NAME   = {MODEL_NAME}")
    print(f"INPUT_DIR    = {input_dir}")
    print(f"OUTPUT_DIR   = {output_dir}")
    print(f"HF_CACHE_DIR = {HF_CACHE_DIR}")
    print(f"USE_4BIT     = {USE_4BIT}")
    print(f"NUM_FILES    = {len(input_files)}")
    print("=" * 80)

    tokenizer, model = load_model_and_tokenizer(MODEL_NAME, USE_4BIT)

    print("=" * 80)
    print("Model loaded successfully.")
    print("=" * 80)

    return tokenizer, model, input_files, output_dir


def run_inference(input_files, output_dir, tokenizer, model):
    print("=" * 80)
    print(f"Running inference on {len(input_files)} files...")
    print("=" * 80)

    for input_path in input_files:
        process_file(
            input_path=input_path,
            output_dir=output_dir,
            tokenizer=tokenizer,
            model=model,
        )

    print("=" * 80)
    print("All files processed.")
    print("=" * 80)

tokenizer, model, input_files, output_dir = prepare_inference()

run_inference(input_files, output_dir, tokenizer, model)

print("\nGenerated files:")
for name in os.listdir(OUTPUT_DIR):
    print(name)

# =========================================================
# 5. Zip outputs
# =========================================================

zip_path = "/content/step3_4_long_prompt_FloorPlan1_olmo2_generated_paragraph.zip"
!zip -r {zip_path} {OUTPUT_DIR}

from google.colab import files
files.download(zip_path)